### ISSUE TITLE
Platform

### ISSUE THREAD

**Issue by beyondguo** [Minqi824/ADBench#4]
It there going to be a platform so I can evaluate my method on it?

**Comment by Minqi824** [comment]
Thank you for addressing this problem! Currently, we provide the [demo](https://github.com/Minqi824/ADBench/blob/main/demo.ipynb) codes for demonstrating examples to evaluate customized algorithms on the datasets mentioned in ADBench, and we also illustrate the generation process of more complex CV and NLP datasets (e.g., 20newsgroups and MVTec-AD) in the [dataset folder](https://github.com/Minqi824/ADBench/tree/main/datasets). Although not perfect, now one can evaluate their customized algorithms on the classical AD datasets, or the CV and NLP datasets embedded by the cutting-edge pre-trained models. For the latter CV and NLP data sources, we also provide two versions (1. ResNet-18 for CV datasets and BERT for NLP datasets; 2. ViT for CV datasets and RoBERTa for NLP datasets), in order to include more comprehensive data sources in the ADBench.

In our long-term plan, we will release the official platform of ADBench to provide a more user-friendly API, please keep following the latest update of our ADBench :)
